### PR TITLE
[explorer] Fix an issue where the closing part of the tag would break on two lines

### LINKED ISSUE #326: [Feedback] Closing part of tag /> can wrap on two lines
# Issue summary

Closing part of the tag doesn't look great (in rare occasions).

## Steps to reproduce

1. Load https://polaris-icons.shopify.com/?icon=AddImageMajor

## Expected behavior

Closing part of the tag `/>` appears on a single line

Screenshot 2019-04-11 12 46 24

## Actual behavior

Closing part of the tag `/>` is broken into two lines.

Screenshot 2019-04-11 12 45 30

### PR DESCRIPTION
**Pull request by kaelig**
Fixes #326

### CODE REVIEW

File: packages/app-icon-explorer/src/components/IconDetailsPanel/components/CodeBlock.tsx [hunk 1]
```diff
@@ -73,8 +74,12 @@ CodeBlock.ImportItems = function ImportItems({children}: BlockProps) {
   return <span className={styles.syntaxImportItems}>{children}</span>;
 };
 
-CodeBlock.Tag = function Tag({children}: BlockProps) {
-  return <span className={styles.syntaxTag}>{children}</span>;
+CodeBlock.Tag = function Tag({children, nobr}: BlockProps & {nobr?: boolean}) {
```
Comment (BPScott) [inline packages/app-icon-explorer/src/components/IconDetailsPanel/components/CodeBlock.tsx]: Can we have a standalone interface for this instead of building it inline?

```ts
interface BlockProps {
  children?: React.ReactNode;
}

interface TagBlockProps extends BlockProps {
  noWrap?: boolean;
}
```

Also thoughts on naming `noWrap`? Feels a little more obvious to me. 



Alternatively should CodeBlock.Tag always never wrap? We wouldn't ever want this either:

```
<
Foo
```

Comment (kaelig) [reply packages/app-icon-explorer/src/components/IconDetailsPanel/components/CodeBlock.tsx]: >Alternatively should CodeBlock.Tag always never wrap? We wouldn't ever want this either:

Good point. Less "intentional" code-wise, but way easier!
